window.HARDWARE_DB['cooler'] = [
  {"name": "猫头鹰 NH-D15", "type": "风冷", "tower": "双塔", "tdp_cooling": 250, "height": 165, "fan_count": 2, "is_e_waste": false, "notes": "顶级风冷, 静音标杆, 但贵", "tier_score": 9, "brand": "猫头鹰"},
  {"name": "猫头鹰 NH-D15 G2", "type": "风冷", "tower": "双塔", "tdp_cooling": 280, "height": 168, "fan_count": 2, "is_e_waste": false, "notes": "D15二代, 8热管, 不对称设计提升兼容性", "tier_score": 9, "brand": "猫头鹰"},
  {"name": "猫头鹰 NH-U12A", "type": "风冷", "tower": "单塔", "tdp_cooling": 230, "height": 158, "fan_count": 2, "is_e_waste": false, "notes": "顶级单塔, NF-A12x25风扇, 兼容性极佳", "tier_score": 6, "brand": "猫头鹰"},
  {"name": "猫头鹰 NH-U12A chromax.black", "type": "风冷", "tower": "单塔", "tdp_cooling": 230, "height": 158, "fan_count": 2, "is_e_waste": false, "notes": "U12A纯黑版", "tier_score": 6, "brand": "猫头鹰"},
  {"name": "猫头鹰 NH-D12L", "type": "风冷", "tower": "双塔", "tdp_cooling": 220, "height": 145, "fan_count": 1, "is_e_waste": false, "notes": "矮双塔, 145mm高, 兼容性出色", "tier_score": 8, "brand": "猫头鹰"},
  {"name": "猫头鹰 NH-U9S", "type": "风冷", "tower": "单塔", "tdp_cooling": 160, "height": 125, "fan_count": 1, "is_e_waste": false, "notes": "9cm迷你塔, ITX绝配", "tier_score": 6, "brand": "猫头鹰"},
  {"name": "猫头鹰 NH-L12S", "type": "风冷", "tower": "下压式", "tdp_cooling": 120, "height": 70, "fan_count": 1, "is_e_waste": false, "notes": "下压式旗舰, ITX小钢炮首选", "tier_score": 3, "brand": "猫头鹰"},
  {"name": "猫头鹰 NH-L9i", "type": "风冷", "tower": "下压式", "tdp_cooling": 95, "height": 37, "fan_count": 1, "is_e_waste": false, "notes": "超薄下压, 仅37mm, ITX极限", "tier_score": 3, "brand": "猫头鹰"},
  {"name": "利民 AX120 R SE", "type": "风冷", "tower": "单塔", "tdp_cooling": 180, "height": 148, "fan_count": 1, "is_e_waste": false, "notes": "百元战神, AGHP逆重力热管", "tier_score": 6, "brand": "利民"},
  {"name": "利民 PA120 SE", "type": "风冷", "tower": "双塔", "tdp_cooling": 240, "height": 155, "fan_count": 2, "is_e_waste": false, "notes": "双塔性价比王, Peerless Assassin青春版", "tier_score": 8, "brand": "利民"},
  {"name": "利民 Peerless Assassin 120", "type": "风冷", "tower": "双塔", "tdp_cooling": 245, "height": 157, "fan_count": 2, "is_e_waste": false, "notes": "PA120标准版, 6热管双塔标杆", "tier_score": 8, "brand": "利民"},
  {"name": "利民 Phantom Spirit 120", "type": "风冷", "tower": "双塔", "tdp_cooling": 265, "height": 157, "fan_count": 2, "is_e_waste": false, "notes": "PS120, 7热管, PA120升级版", "tier_score": 9, "brand": "利民"},
  {"name": "利民 PS120 EVO", "type": "风冷", "tower": "双塔", "tdp_cooling": 260, "height": 157, "fan_count": 2, "is_e_waste": false, "notes": "Phantom Spirit进化版", "tier_score": 9, "brand": "利民"},
  {"name": "利民 FC140", "type": "风冷", "tower": "双塔", "tdp_cooling": 275, "height": 160, "fan_count": 2, "is_e_waste": false, "notes": "风冷之王, 5根8mm热管", "tier_score": 9, "brand": "利民"},
  {"name": "利民 FC140 WHITE", "type": "风冷", "tower": "双塔", "tdp_cooling": 275, "height": 160, "fan_count": 2, "is_e_waste": false, "notes": "FC140白色版", "tier_score": 9, "brand": "利民"},
  {"name": "利民 Burst Assassin 120", "type": "风冷", "tower": "单塔", "tdp_cooling": 200, "height": 154, "fan_count": 1, "is_e_waste": false, "notes": "BA120, 6热管单塔, 性价比单塔", "tier_score": 6, "brand": "利民"},
  {"name": "利民 FS140 White", "type": "风冷", "tower": "双塔", "tdp_cooling": 250, "height": 160, "fan_count": 2, "is_e_waste": false, "notes": "Frost Spirit白化版", "tier_score": 9, "brand": "利民"},
  {"name": "利民 冰封幻境360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "Frozen Magic 360, 高性价比水冷", "tier_score": 9, "brand": "利民"},
  {"name": "利民 冰封远景360 V2", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "Frozen Horizon 360 V2, 旗舰级", "tier_score": 9, "brand": "利民"},
  {"name": "利民 Frozen Prism 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "冰封棱镜360, 带LCD屏幕", "tier_score": 10, "brand": "利民"},
  {"name": "利民 Frozen Prism 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": true, "fan_count": 2, "is_e_waste": false, "notes": "冰封棱镜240, 带LCD屏幕", "tier_score": 7, "brand": "利民"},
  {"name": "利民 Aqua Elite 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "Aqua Elite 360, 入门水冷", "tier_score": 9, "brand": "利民"},
  {"name": "利民 Aqua Elite 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "Aqua Elite 240, 入门240水冷", "tier_score": 6, "brand": "利民"},
  {"name": "九州风神 AK120 SE", "type": "风冷", "tower": "单塔", "tdp_cooling": 180, "height": 150, "fan_count": 1, "is_e_waste": false, "notes": "百元标杆单塔", "tier_score": 6, "brand": "九州风神"},
  {"name": "九州风神 AK400", "type": "风冷", "tower": "单塔", "tdp_cooling": 220, "height": 155, "fan_count": 1, "is_e_waste": false, "notes": "主流单塔, 4热管", "tier_score": 6, "brand": "九州风神"},
  {"name": "九州风神 AK500", "type": "风冷", "tower": "单塔", "tdp_cooling": 240, "height": 158, "fan_count": 1, "is_e_waste": false, "notes": "大单塔, 5热管", "tier_score": 6, "brand": "九州风神"},
  {"name": "九州风神 AG400", "type": "风冷", "tower": "单塔", "tdp_cooling": 200, "height": 150, "fan_count": 1, "is_e_waste": false, "notes": "AG系列入门单塔", "tier_score": 6, "brand": "九州风神"},
  {"name": "九州风神 AK620", "type": "风冷", "tower": "双塔", "tdp_cooling": 260, "height": 160, "fan_count": 2, "is_e_waste": false, "notes": "双塔旗舰, 压旗舰U无压力", "tier_score": 9, "brand": "九州风神"},
  {"name": "九州风神 AK620 Digital", "type": "风冷", "tower": "双塔", "tdp_cooling": 260, "height": 160, "fan_count": 2, "is_e_waste": false, "notes": "双塔带数显屏", "tier_score": 9, "brand": "九州风神"},
  {"name": "九州风神 AG620", "type": "风冷", "tower": "双塔", "tdp_cooling": 250, "height": 157, "fan_count": 2, "is_e_waste": false, "notes": "AG系列双塔", "tier_score": 9, "brand": "九州风神"},
  {"name": "九州风神 阿萨辛4S", "type": "风冷", "tower": "双塔", "tdp_cooling": 280, "height": 164, "fan_count": 2, "is_e_waste": false, "notes": "旗舰双塔, Assassin IV, 7热管", "tier_score": 9, "brand": "九州风神"},
  {"name": "九州风神 冰堡垒360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "冰堡垒360经典款", "tier_score": 8, "brand": "九州风神"},
  {"name": "九州风神 冰堡垒360 V2", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "冰堡垒360二代, 性能提升", "tier_score": 8, "brand": "九州风神"},
  {"name": "九州风神 冰堡垒240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "冰堡垒240", "tier_score": 5, "brand": "九州风神"},
  {"name": "九州风神 冰魔方360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "冰魔方360, 磁吸LCD屏幕", "tier_score": 9, "brand": "九州风神"},
  {"name": "九州风神 冰魔方240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": true, "fan_count": 2, "is_e_waste": false, "notes": "冰魔方240, 磁吸LCD屏幕", "tier_score": 6, "brand": "九州风神"},
  {"name": "九州风神 LT720", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "LT系列360, 高性能", "tier_score": 8, "brand": "九州风神"},
  {"name": "九州风神 LT520", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "LT系列240", "tier_score": 5, "brand": "九州风神"},
  {"name": "瓦尔基里 C360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "高性能360水冷, C系列", "tier_score": 8, "brand": "瓦尔基里"},
  {"name": "瓦尔基里 C240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "C系列240", "tier_score": 5, "brand": "瓦尔基里"},
  {"name": "瓦尔基里 A360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "A系列360, 性价比之选", "tier_score": 8, "brand": "瓦尔基里"},
  {"name": "瓦尔基里 A240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "A系列240", "tier_score": 5, "brand": "瓦尔基里"},
  {"name": "瓦尔基里 B360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "B系列360, 性价比360", "tier_score": 8, "brand": "瓦尔基里"},
  {"name": "瓦尔基里 B240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 250, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "B系列240", "tier_score": 5, "brand": "瓦尔基里"},
  {"name": "瓦尔基里 GL360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "GL系列360, 高性能", "tier_score": 8, "brand": "瓦尔基里"},
  {"name": "瓦尔基里 GL240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "GL系列240", "tier_score": 5, "brand": "瓦尔基里"},
  {"name": "瓦尔基里 E360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 350, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "旗舰E360, 2.4寸LCD屏, 强冷", "tier_score": 9, "brand": "瓦尔基里"},
  {"name": "瓦尔基里 V36 AMG", "type": "水冷", "radiator_size": 360, "tdp_cooling": 350, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "AMG联名旗舰, LCD屏", "tier_score": 9, "brand": "瓦尔基里"},
  {"name": "瓦尔基里 SL125", "type": "风冷", "tower": "单塔", "tdp_cooling": 230, "height": 155, "fan_count": 1, "is_e_waste": false, "notes": "SL125单塔风冷, 6热管", "tier_score": 5, "brand": "瓦尔基里"},
  {"name": "瓦尔基里 R125", "type": "风冷", "tower": "双塔", "tdp_cooling": 250, "height": 160, "fan_count": 2, "is_e_waste": false, "notes": "R125双塔风冷, 7热管", "tier_score": 8, "brand": "瓦尔基里"},
  {"name": "酷冷至尊 Hyper 212 黑化版", "type": "风冷", "tower": "单塔", "tdp_cooling": 180, "height": 158, "fan_count": 1, "is_e_waste": false, "notes": "经典单塔, 黑化设计", "tier_score": 5, "brand": "酷冷至尊"},
  {"name": "酷冷至尊 暴雪T620S", "type": "风冷", "tower": "双塔", "tdp_cooling": 240, "height": 159, "fan_count": 2, "is_e_waste": false, "notes": "双塔, 6热管", "tier_score": 7, "brand": "酷冷至尊"},
  {"name": "酷冷至尊 暴雪T620", "type": "风冷", "tower": "双塔", "tdp_cooling": 260, "height": 160, "fan_count": 2, "is_e_waste": false, "notes": "暴雪T620标准版, 6热管", "tier_score": 8, "brand": "酷冷至尊"},
  {"name": "酷冷至尊 暴雪T824", "type": "风冷", "tower": "双塔", "tdp_cooling": 300, "height": 165, "fan_count": 2, "is_e_waste": false, "notes": "旗舰双塔, 8热管, 风冷天花板", "tier_score": 8, "brand": "酷冷至尊"},
  {"name": "酷冷至尊 海魔360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "MasterLiquid ML360L, 经典360水冷", "tier_score": 8, "brand": "酷冷至尊"},
  {"name": "酷冷至尊 ML360L V2", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "ML360L二代, 升级水泵", "tier_score": 8, "brand": "酷冷至尊"},
  {"name": "酷冷至尊 MasterLiquid 360L Core", "type": "水冷", "radiator_size": 360, "tdp_cooling": 310, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "360L Core, 新款入门360", "tier_score": 8, "brand": "酷冷至尊"},
  {"name": "酷冷至尊 MasterLiquid 240L Core", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "240L Core, 新款入门240", "tier_score": 5, "brand": "酷冷至尊"},
  {"name": "酷冷至尊 炎神P360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 350, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "旗舰水冷, 带LCD屏幕", "tier_score": 9, "brand": "酷冷至尊"},
  {"name": "酷冷至尊 冰神G360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "冰神G360, 双泵设计", "tier_score": 8, "brand": "酷冷至尊"},
  {"name": "追风者 S5", "type": "风冷", "tower": "单塔", "tdp_cooling": 180, "height": 148, "fan_count": 1, "is_e_waste": false, "notes": "入门单塔", "tier_score": 5, "brand": "追风者"},
  {"name": "追风者 Polar T6-120", "type": "风冷", "tower": "单塔", "tdp_cooling": 220, "height": 155, "fan_count": 1, "is_e_waste": false, "notes": "Polar系列单塔, 6热管", "tier_score": 5, "brand": "追风者"},
  {"name": "追风者 TC14PE", "type": "风冷", "tower": "双塔", "tdp_cooling": 250, "height": 160, "fan_count": 2, "is_e_waste": false, "notes": "追风者双塔旗舰, 14cm双塔", "tier_score": 8, "brand": "追风者"},
  {"name": "追风者 Glacier One 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "Asetek 7代方案", "tier_score": 5, "brand": "追风者"},
  {"name": "追风者 Glacier One 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "Asetek 7代方案", "tier_score": 8, "brand": "追风者"},
  {"name": "追风者 Glacier One 360 M25", "type": "水冷", "radiator_size": 360, "tdp_cooling": 310, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "M25风扇版360", "tier_score": 8, "brand": "追风者"},
  {"name": "追风者 Glacier One 360 T30", "type": "水冷", "radiator_size": 360, "tdp_cooling": 330, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "T30 30mm厚扇版, 性能强化", "tier_score": 8, "brand": "追风者"},
  {"name": "追风者 Glacier One 240 T30", "type": "水冷", "radiator_size": 240, "tdp_cooling": 280, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "T30风扇240版", "tier_score": 5, "brand": "追风者"},
  {"name": "ROG STRIX LC 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "ROG信仰, Asetek方案", "tier_score": 8, "brand": "华硕"},
  {"name": "ROG STRIX LC II 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "ROG二代240, ARGB", "tier_score": 5, "brand": "华硕"},
  {"name": "ROG STRIX LC III 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "ROG三代360, 新款Asetek", "tier_score": 8, "brand": "华硕"},
  {"name": "ROG 龙神3 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "ROG旗舰, 3.5寸LCD屏, Asetek 8代", "tier_score": 9, "brand": "华硕"},
  {"name": "ROG 龙王III 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "龙王三代360, Asetek 8代", "tier_score": 8, "brand": "华硕"},
  {"name": "ROG 龙王III 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "龙王三代240", "tier_score": 5, "brand": "华硕"},
  {"name": "超频三 东海R4000", "type": "风冷", "tower": "单塔", "tdp_cooling": 200, "height": 155, "fan_count": 1, "is_e_waste": false, "notes": "东海系列, 4热管单塔", "tier_score": 5, "brand": "超频三"},
  {"name": "超频三 K6", "type": "风冷", "tower": "单塔", "tdp_cooling": 220, "height": 155, "fan_count": 1, "is_e_waste": false, "notes": "K6单塔, 6热管", "tier_score": 5, "brand": "超频三"},
  {"name": "超频三 G6", "type": "风冷", "tower": "双塔", "tdp_cooling": 240, "height": 158, "fan_count": 2, "is_e_waste": false, "notes": "G6双塔", "tier_score": 7, "brand": "超频三"},
  {"name": "超频三 RZ620", "type": "风冷", "tower": "双塔", "tdp_cooling": 260, "height": 160, "fan_count": 2, "is_e_waste": false, "notes": "RZ620双塔, 6热管", "tier_score": 8, "brand": "超频三"},
  {"name": "超频三 凛冬 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "凛冬360水冷", "tier_score": 8, "brand": "超频三"},
  {"name": "超频三 DS360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "DS360旗舰, 带数显屏", "tier_score": 9, "brand": "超频三"},
  {"name": "先马 冰雨", "type": "风冷", "tower": "单塔", "tdp_cooling": 180, "height": 150, "fan_count": 1, "is_e_waste": false, "notes": "冰雨入门单塔", "tier_score": 4, "brand": "先马"},
  {"name": "先马 冰界240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "冰界240, 高性价比240水冷", "tier_score": 4, "brand": "先马"},
  {"name": "先马 冰界360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "冰界360, 高性价比360水冷", "tier_score": 7, "brand": "先马"},
  {"name": "先马 XW240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "XW系列240, ARGB", "tier_score": 4, "brand": "先马"},
  {"name": "先马 XW360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "高性价比360水冷", "tier_score": 7, "brand": "先马"},
  {"name": "先马 XW360 Plus", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "XW360 Plus, 带LCD屏", "tier_score": 8, "brand": "先马"},
  {"name": "钛坦 A090", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "入门360水冷", "tier_score": 8, "brand": "其他"},
  {"name": "钛坦 LG240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "LG系列240", "tier_score": 5, "brand": "其他"},
  {"name": "钛坦 LG360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 310, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "LG系列360, Asetek方案", "tier_score": 8, "brand": "其他"},
  {"name": "钛坦 LG420", "type": "水冷", "radiator_size": 420, "tdp_cooling": 350, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "LG系列420, 14cm×3", "tier_score": 9, "brand": "其他"},
  {"name": "钛坦 SJ-A080", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "SJ-A080, 带LCD屏幕", "tier_score": 9, "brand": "其他"},
  {"name": "ID-COOLING SE-224-XTS", "type": "风冷", "tower": "单塔", "tdp_cooling": 180, "height": 151, "fan_count": 1, "is_e_waste": false, "notes": "入门单塔, 4热管", "tier_score": 5, "brand": "ID-COOLING"},
  {"name": "ID-COOLING SE-226-XT", "type": "风冷", "tower": "单塔", "tdp_cooling": 220, "height": 156, "fan_count": 1, "is_e_waste": false, "notes": "SE-226-XT, 6热管单塔", "tier_score": 5, "brand": "ID-COOLING"},
  {"name": "ID-COOLING SE-207-XT", "type": "风冷", "tower": "双塔", "tdp_cooling": 250, "height": 157, "fan_count": 2, "is_e_waste": false, "notes": "SE-207-XT双塔, 7热管", "tier_score": 8, "brand": "ID-COOLING"},
  {"name": "ID-COOLING FROSTFLOW X 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "FROSTFLOW X 240, 入门240", "tier_score": 5, "brand": "ID-COOLING"},
  {"name": "ID-COOLING FROSTFLOW X 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "入门360水冷", "tier_score": 8, "brand": "ID-COOLING"},
  {"name": "ID-COOLING DASHFLOW 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 310, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "DASHFLOW 360, 带LCD屏幕", "tier_score": 9, "brand": "ID-COOLING"},
  {"name": "大镰刀 赤兔马", "type": "风冷", "tower": "单塔", "tdp_cooling": 180, "height": 152, "fan_count": 1, "is_e_waste": false, "notes": "赤兔马单塔, 4热管, 高性价比", "tier_score": 5, "brand": "大镰刀"},
  {"name": "大镰刀 Mugen 6", "type": "风冷", "tower": "单塔", "tdp_cooling": 230, "height": 154, "fan_count": 1, "is_e_waste": false, "notes": "Mugen 6, 6热管, 日系静音", "tier_score": 5, "brand": "大镰刀"},
  {"name": "大镰刀 Fuma 3", "type": "风冷", "tower": "双塔", "tdp_cooling": 250, "height": 155, "fan_count": 2, "is_e_waste": false, "notes": "Fuma 3双塔, 6热管, 静音标杆", "tier_score": 8, "brand": "大镰刀"},
  {"name": "大镰刀 Ninja 5", "type": "风冷", "tower": "双塔", "tdp_cooling": 230, "height": 155, "fan_count": 2, "is_e_waste": false, "notes": "忍者5代, 双塔静音", "tier_score": 7, "brand": "大镰刀"},
  {"name": "AMD原装散热器", "type": "风冷", "tower": "下压式", "tdp_cooling": 95, "height": 70, "fan_count": 1, "is_e_waste": false, "notes": "随CPU附赠, 仅适合65W级别", "tier_score": 2, "brand": "AMD"},
  {"name": "Intel原装散热器", "type": "风冷", "tower": "下压式", "tdp_cooling": 65, "height": 50, "fan_count": 1, "is_e_waste": false, "notes": "仅适合i3级, K系列不带", "tier_score": 2, "brand": "Intel"},
  {"name": "Prolimatech PK-3 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "老牌散热品牌, 240水冷", "tier_score": 5, "brand": "其他"},
  {"name": "Prolimatech PK-3 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "老牌散热品牌, 360水冷", "tier_score": 8, "brand": "其他"},
  {"name": "海盗船 H100i Elite Capellix", "type": "水冷", "radiator_size": 240, "tdp_cooling": 280, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "H100i精英版, Capellix LED", "tier_score": 6, "brand": "海盗船"},
  {"name": "海盗船 H100i Elite LCD", "type": "水冷", "radiator_size": 240, "tdp_cooling": 280, "has_screen": true, "fan_count": 2, "is_e_waste": false, "notes": "H100i LCD版, 2.1寸IPS屏", "tier_score": 7, "brand": "海盗船"},
  {"name": "海盗船 H150i Elite Capellix", "type": "水冷", "radiator_size": 360, "tdp_cooling": 330, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "H150i精英版, CoolIT方案", "tier_score": 9, "brand": "海盗船"},
  {"name": "海盗船 H150i Elite LCD", "type": "水冷", "radiator_size": 360, "tdp_cooling": 330, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "H150i LCD版, 2.1寸IPS屏", "tier_score": 10, "brand": "海盗船"},
  {"name": "海盗船 H170i Elite Capellix", "type": "水冷", "radiator_size": 420, "tdp_cooling": 360, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "H170i精英版, 14cm×3 420水冷", "tier_score": 10, "brand": "海盗船"},
  {"name": "海盗船 H115i Elite Capellix", "type": "水冷", "radiator_size": 280, "tdp_cooling": 300, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "H115i精英版, 14cm×2 280水冷", "tier_score": 8, "brand": "海盗船"},
  {"name": "NZXT Kraken X53", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "Kraken X53, Asetek 7代, 镜面泵头", "tier_score": 6, "brand": "NZXT"},
  {"name": "NZXT Kraken X63", "type": "水冷", "radiator_size": 280, "tdp_cooling": 300, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "Kraken X63, 280水冷, 性能标杆", "tier_score": 8, "brand": "NZXT"},
  {"name": "NZXT Kraken X73", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "Kraken X73, 360水冷旗舰", "tier_score": 9, "brand": "NZXT"},
  {"name": "NZXT Kraken Elite 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 270, "has_screen": true, "fan_count": 2, "is_e_waste": false, "notes": "Kraken Elite 240, 2.36寸LCD", "tier_score": 7, "brand": "NZXT"},
  {"name": "NZXT Kraken Elite 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 330, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "Kraken Elite 360, 2.36寸LCD", "tier_score": 10, "brand": "NZXT"},
  {"name": "NZXT Kraken 360 RGB", "type": "水冷", "radiator_size": 360, "tdp_cooling": 310, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "新款Kraken 360, RGB风扇", "tier_score": 9, "brand": "NZXT"},
  {"name": "乔思伯 CR-1400", "type": "风冷", "tower": "单塔", "tdp_cooling": 160, "height": 126, "fan_count": 1, "is_e_waste": false, "notes": "CR-1400矮塔, 4热管, ITX优选", "tier_score": 5, "brand": "乔思伯"},
  {"name": "乔思伯 CR-3000", "type": "风冷", "tower": "双塔", "tdp_cooling": 260, "height": 160, "fan_count": 2, "is_e_waste": false, "notes": "CR-3000双塔, 7热管", "tier_score": 8, "brand": "乔思伯"},
  {"name": "乔思伯 HX7280", "type": "风冷", "tower": "双塔", "tdp_cooling": 280, "height": 160, "fan_count": 2, "is_e_waste": false, "notes": "HX7280双塔旗舰, 7热管", "tier_score": 8, "brand": "乔思伯"},
  {"name": "乔思伯 TW-240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 250, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "TW系列240, 入门ARGB水冷", "tier_score": 5, "brand": "乔思伯"},
  {"name": "乔思伯 TW-360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "TW系列360, ARGB", "tier_score": 8, "brand": "乔思伯"},
  {"name": "乔思伯 光影360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 310, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "光影360, 无限镜面+LCD", "tier_score": 9, "brand": "乔思伯"},
  {"name": "微星 MAG CoreLiquid 240R V2", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "MAG 240R V2, 冷头内嵌水泵", "tier_score": 5, "brand": "微星"},
  {"name": "微星 MAG CoreLiquid 360R V2", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "MAG 360R V2, 冷头内嵌水泵", "tier_score": 8, "brand": "微星"},
  {"name": "微星 MAG CoreLiquid E360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 310, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "MAG E360, 新款入门360", "tier_score": 8, "brand": "微星"},
  {"name": "微星 MAG CoreLiquid E240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "MAG E240, 新款入门240", "tier_score": 5, "brand": "微星"},
  {"name": "微星 MEG CoreLiquid S360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 330, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "MEG旗舰, 2.4寸IPS屏, Asetek", "tier_score": 9, "brand": "微星"},
  {"name": "联力 Galahad II Trinity 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 270, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "Galahad II 240, 性能标杆", "tier_score": 5, "brand": "联力"},
  {"name": "联力 Galahad II Trinity 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 330, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "Galahad II 360, 性能标杆", "tier_score": 8, "brand": "联力"},
  {"name": "联力 Galahad II LCD 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 270, "has_screen": true, "fan_count": 2, "is_e_waste": false, "notes": "Galahad II LCD 240, 2.88寸IPS", "tier_score": 6, "brand": "联力"},
  {"name": "联力 Galahad II LCD 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 330, "has_screen": true, "fan_count": 3, "is_e_waste": false, "notes": "Galahad II LCD 360, 2.88寸IPS", "tier_score": 9, "brand": "联力"},
  {"name": "联力 Galahad II Performance 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 350, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "Galahad II 性能版360, 30mm厚排", "tier_score": 8, "brand": "联力"},
  {"name": "be quiet! Dark Rock 4", "type": "风冷", "tower": "单塔", "tdp_cooling": 200, "height": 159, "fan_count": 1, "is_e_waste": false, "notes": "Dark Rock 4, 德系静音, 6热管", "tier_score": 5, "brand": "其他"},
  {"name": "be quiet! Dark Rock Pro 4", "type": "风冷", "tower": "双塔", "tdp_cooling": 250, "height": 163, "fan_count": 2, "is_e_waste": false, "notes": "Dark Rock Pro 4, 7热管, 静音王", "tier_score": 8, "brand": "其他"},
  {"name": "be quiet! Dark Rock Pro 5", "type": "风冷", "tower": "双塔", "tdp_cooling": 270, "height": 168, "fan_count": 2, "is_e_waste": false, "notes": "Dark Rock Pro 5新款, 性能提升", "tier_score": 8, "brand": "其他"},
  {"name": "be quiet! Pure Loop 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "Pure Loop 240, 外置水泵, 静音", "tier_score": 5, "brand": "其他"},
  {"name": "be quiet! Pure Loop 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 310, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "Pure Loop 360, 外置水泵, 静音", "tier_score": 8, "brand": "其他"},
  {"name": "爱国者 冰魄 K4", "type": "风冷", "tower": "单塔", "tdp_cooling": 180, "height": 150, "fan_count": 1, "is_e_waste": false, "notes": "冰魄K4, 4热管单塔", "tier_score": 4, "brand": "爱国者"},
  {"name": "爱国者 冰魄 V5", "type": "风冷", "tower": "双塔", "tdp_cooling": 220, "height": 155, "fan_count": 2, "is_e_waste": false, "notes": "冰魄V5双塔, 5热管", "tier_score": 6, "brand": "爱国者"},
  {"name": "爱国者 冰魄 V6", "type": "风冷", "tower": "双塔", "tdp_cooling": 250, "height": 158, "fan_count": 2, "is_e_waste": false, "notes": "冰魄V6双塔, 6热管", "tier_score": 7, "brand": "爱国者"},
  {"name": "爱国者 冰峰 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 250, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "冰峰240, 入门ARGB水冷", "tier_score": 4, "brand": "爱国者"},
  {"name": "爱国者 冰峰 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 300, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "冰峰360, ARGB", "tier_score": 7, "brand": "爱国者"},
  {"name": "雅浚 Basic B3", "type": "风冷", "tower": "单塔", "tdp_cooling": 180, "height": 148, "fan_count": 1, "is_e_waste": false, "notes": "Basic B3, 4热管单塔, 百元级", "tier_score": 5, "brand": "雅浚"},
  {"name": "雅浚 Basic B5", "type": "风冷", "tower": "双塔", "tdp_cooling": 240, "height": 155, "fan_count": 2, "is_e_waste": false, "notes": "Basic B5双塔, 6热管", "tier_score": 7, "brand": "雅浚"},
  {"name": "雅浚 EA3 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 260, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "EA3 240, 入门水冷", "tier_score": 5, "brand": "雅浚"},
  {"name": "雅浚 EA5 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 270, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "EA5 240, 中端水冷", "tier_score": 5, "brand": "雅浚"},
  {"name": "雅浚 EA5 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 320, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "EA5 360, 高性能水冷", "tier_score": 8, "brand": "雅浚"},
  {"name": "安耐美 ETS-T50", "type": "风冷", "tower": "单塔", "tdp_cooling": 220, "height": 160, "fan_count": 1, "is_e_waste": false, "notes": "ETS-T50, 5热管单塔", "tier_score": 5, "brand": "其他"},
  {"name": "安耐美 LIQTECH 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 270, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "LIQTECH 240, 高耐久", "tier_score": 5, "brand": "其他"},
  {"name": "安耐美 LIQTECH 280", "type": "水冷", "radiator_size": 280, "tdp_cooling": 300, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "LIQTECH 280", "tier_score": 7, "brand": "其他"},
  {"name": "安耐美 LIQTECH 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 330, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "LIQTECH 360, 高耐久", "tier_score": 8, "brand": "其他"},
  {"name": "赛普雷 幻彩", "type": "风冷", "tower": "单塔", "tdp_cooling": 160, "height": 148, "fan_count": 1, "is_e_waste": false, "notes": "幻彩入门单塔, RGB", "tier_score": 4, "brand": "赛普雷"},
  {"name": "赛普雷 V587", "type": "风冷", "tower": "双塔", "tdp_cooling": 240, "height": 158, "fan_count": 2, "is_e_waste": false, "notes": "V587双塔, 6热管", "tier_score": 6, "brand": "赛普雷"},
  {"name": "赛普雷 冷山 240", "type": "水冷", "radiator_size": 240, "tdp_cooling": 250, "has_screen": false, "fan_count": 2, "is_e_waste": false, "notes": "冷山240, 入门240水冷", "tier_score": 4, "brand": "赛普雷"},
  {"name": "赛普雷 冷山 360", "type": "水冷", "radiator_size": 360, "tdp_cooling": 290, "has_screen": false, "fan_count": 3, "is_e_waste": false, "notes": "冷山360, 入门360水冷", "tier_score": 7, "brand": "赛普雷"},
  {"name": "Arctic Liquid Freezer III Pro 360 ARGB", "brand": "Arctic", "type": "360水冷", "tier_score": 8, "msrp_cny": 699},
  {"name": "Arctic Liquid Freezer III Pro 420 ARGB", "brand": "Arctic", "type": "420水冷", "tier_score": 9, "msrp_cny": 799},
  {"name": "Arctic Liquid Freezer III 280 ARGB", "brand": "Arctic", "type": "280水冷", "tier_score": 7, "msrp_cny": 549},
  {"name": "NZXT Kraken Elite 360 (2024)", "brand": "NZXT", "type": "360水冷", "tier_score": 9, "msrp_cny": 1999},
  {"name": "NZXT Kraken Elite 280 (2024)", "brand": "NZXT", "type": "280水冷", "tier_score": 8, "msrp_cny": 1699},
  {"name": "九州风神 冰暴 360 ARGB", "brand": "九州风神", "type": "360水冷", "tier_score": 8, "msrp_cny": 499},
  {"name": "九州风神 冰暴 240 ARGB", "brand": "九州风神", "type": "240水冷", "tier_score": 5, "msrp_cny": 399},
  {"name": "九州风神 ASSASSIN IV VC", "brand": "九州风神", "type": "双塔风冷", "tier_score": 8, "msrp_cny": 459},
  {"name": "酷冷至尊 MasterLiquid 360 冰界 幻屏", "brand": "酷冷至尊", "type": "360水冷", "tier_score": 8, "msrp_cny": 1699},
  {"name": "酷冷至尊 Hyper 612 APEX", "brand": "酷冷至尊", "type": "单塔风冷", "tier_score": 5, "msrp_cny": 249},
  {"name": "瓦尔基里 V360 LOKI", "brand": "瓦尔基里", "type": "360水冷", "tier_score": 8, "msrp_cny": 1299},
  {"name": "微星 MAG CORELIQUID I360", "brand": "微星", "type": "360水冷", "tier_score": 8, "msrp_cny": 699},
  {"name": "海盗船 iCUE LINK H150i LCD", "brand": "海盗船", "type": "360水冷", "tier_score": 4, "msrp_cny": 2299},
  {"name": "利民 AK120 SE ARGB", "brand": "利民", "cooler_type": "单塔", "height": 148, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "利民 AK120 SE WH ARGB", "brand": "利民", "cooler_type": "单塔", "height": 148, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "利民 AK120 MINI BLACK", "brand": "利民", "cooler_type": "下压", "height": 88, "fan_count": 1, "radiator_size": "120mm(薄)", "tdp": 135, "noise_level": "30dBA", "tier_score": 4},
  {"name": "利民 AK120 MINI WHITE", "brand": "利民", "cooler_type": "下压", "height": 88, "fan_count": 1, "radiator_size": "120mm(薄)", "tdp": 135, "noise_level": "30dBA", "tier_score": 4},
  {"name": "利民 AK120 DIGITAL", "brand": "利民", "cooler_type": "单塔", "height": 156, "fan_count": 1, "radiator_size": "120mm", "tdp": 200, "noise_level": "30dBA", "tier_score": 5},
  {"name": "利民 AK120 DIGITAL ARGB", "brand": "利民", "cooler_type": "单塔", "height": 156, "fan_count": 1, "radiator_size": "120mm", "tdp": 200, "noise_level": "30dBA", "tier_score": 5},
  {"name": "利民 AK120 PLUS", "brand": "利民", "cooler_type": "单塔", "height": 154, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 220, "noise_level": "30dBA", "tier_score": 6},
  {"name": "利民 PA120", "brand": "利民", "cooler_type": "双塔", "height": 157, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 245, "noise_level": "30dBA", "tier_score": 7},
  {"name": "利民 PA120 SE ARGB", "brand": "利民", "cooler_type": "双塔", "height": 155, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 240, "noise_level": "30dBA", "tier_score": 6},
  {"name": "利民 PA120 SE WHITE ARGB", "brand": "利民", "cooler_type": "双塔", "height": 155, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 240, "noise_level": "30dBA", "tier_score": 6},
  {"name": "利民 PA120 MINI", "brand": "利民", "cooler_type": "双塔", "height": 135, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 220, "noise_level": "30dBA", "tier_score": 6},
  {"name": "利民 PS120SE ARGB", "brand": "利民", "cooler_type": "双塔", "height": 155, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 260, "noise_level": "30dBA", "tier_score": 7},
  {"name": "利民 FC140 BLACK", "brand": "利民", "cooler_type": "双塔", "height": 160, "fan_count": 2, "radiator_size": "140mm+120mm", "tdp": 275, "noise_level": "30dBA", "tier_score": 8},
  {"name": "利民 FS140 BLACK", "brand": "利民", "cooler_type": "双塔", "height": 160, "fan_count": 2, "radiator_size": "140mm×2", "tdp": 280, "noise_level": "30dBA", "tier_score": 8},
  {"name": "利民 U120EX REV.4", "brand": "利民", "cooler_type": "单塔", "height": 157, "fan_count": 1, "radiator_size": "120mm", "tdp": 220, "noise_level": "30dBA", "tier_score": 6},
  {"name": "利民 U120EX REV.4 WHITE", "brand": "利民", "cooler_type": "单塔", "height": 157, "fan_count": 1, "radiator_size": "120mm", "tdp": 220, "noise_level": "30dBA", "tier_score": 6},
  {"name": "利民 BA120", "brand": "利民", "cooler_type": "单塔", "height": 156, "fan_count": 1, "radiator_size": "120mm", "tdp": 190, "noise_level": "30dBA", "tier_score": 5},
  {"name": "利民 BA120 ARGB", "brand": "利民", "cooler_type": "单塔", "height": 156, "fan_count": 1, "radiator_size": "120mm", "tdp": 190, "noise_level": "30dBA", "tier_score": 5},
  {"name": "利民 SI-100", "brand": "利民", "cooler_type": "下压", "height": 100, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "利民 TA120 EX", "brand": "利民", "cooler_type": "单塔", "height": 157, "fan_count": 1, "radiator_size": "120mm", "tdp": 230, "noise_level": "30dBA", "tier_score": 6},
  {"name": "利民 AX120 R SE ARGB WHITE", "brand": "利民", "cooler_type": "单塔", "height": 148, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "利民 AX120 R SE WHITE ARGB", "brand": "利民", "cooler_type": "单塔", "height": 148, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "利民 AX120R SE PLUS", "brand": "利民", "cooler_type": "单塔", "height": 150, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 220, "noise_level": "30dBA", "tier_score": 6},
  {"name": "利民 TA140 EX", "brand": "利民", "cooler_type": "单塔", "height": 160, "fan_count": 1, "radiator_size": "140mm", "tdp": 250, "noise_level": "30dBA", "tier_score": 7},
  {"name": "利民 TS120 MINI", "brand": "利民", "cooler_type": "单塔", "height": 135, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "利民 Frozen Edge 240 WHITE ARGB", "brand": "利民", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 300, "noise_level": "32dBA", "tier_score": 7},
  {"name": "利民 Frozen Edge 240 BLACK ARGB", "brand": "利民", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 300, "noise_level": "32dBA", "tier_score": 7},
  {"name": "利民 Frozen Prism 360 WHITE ARGB", "brand": "利民", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 350, "noise_level": "33dBA", "tier_score": 8},
  {"name": "利民 Frozen Prism 360 BLACK ARGB", "brand": "利民", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 350, "noise_level": "33dBA", "tier_score": 8},
  {"name": "利民 Frozen Notte 240 ARGB", "brand": "利民", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 280, "noise_level": "33dBA", "tier_score": 6},
  {"name": "利民 Frozen Notte 360 ARGB", "brand": "利民", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 330, "noise_level": "33dBA", "tier_score": 7},
  {"name": "利民 Frozen Vision 360", "brand": "利民", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 360, "noise_level": "30dBA", "tier_score": 9},
  {"name": "利民 Frozen Infinity 360", "brand": "利民", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 370, "noise_level": "30dBA", "tier_score": 9},
  {"name": "利民 Frozen Warframe 240", "brand": "利民", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 320, "noise_level": "30dBA", "tier_score": 8},
  {"name": "利民 Frozen Warframe 360", "brand": "利民", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 380, "noise_level": "28dBA", "tier_score": 9},
  {"name": "利民 Frozen Grand Vision 360", "brand": "利民", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 380, "noise_level": "28dBA", "tier_score": 10},
  {"name": "九州风神 大霜塔V5", "brand": "九州风神", "cooler_type": "双塔", "height": 158, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 260, "noise_level": "30dBA", "tier_score": 7},
  {"name": "九州风神 大霜塔V5 ARGB", "brand": "九州风神", "cooler_type": "双塔", "height": 158, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 260, "noise_level": "30dBA", "tier_score": 7},
  {"name": "九州风神 大霜塔V5 WHITE", "brand": "九州风神", "cooler_type": "双塔", "height": 158, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 260, "noise_level": "30dBA", "tier_score": 7},
  {"name": "九州风神 玄冰400 V5", "brand": "九州风神", "cooler_type": "单塔", "height": 155, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "九州风神 玄冰400 V5 ARGB WHITE", "brand": "九州风神", "cooler_type": "单塔", "height": 155, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "九州风神 冰立方400", "brand": "九州风神", "cooler_type": "单塔", "height": 156, "fan_count": 1, "radiator_size": "120mm", "tdp": 200, "noise_level": "30dBA", "tier_score": 5},
  {"name": "九州风神 冰立方400 WH", "brand": "九州风神", "cooler_type": "单塔", "height": 156, "fan_count": 1, "radiator_size": "120mm", "tdp": 200, "noise_level": "30dBA", "tier_score": 5},
  {"name": "九州风神 冰立方620", "brand": "九州风神", "cooler_type": "双塔", "height": 160, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 260, "noise_level": "30dBA", "tier_score": 7},
  {"name": "九州风神 冰立方620 WH", "brand": "九州风神", "cooler_type": "双塔", "height": 160, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 260, "noise_level": "30dBA", "tier_score": 7},
  {"name": "九州风神 AK500 WH", "brand": "九州风神", "cooler_type": "单塔", "height": 160, "fan_count": 1, "radiator_size": "120mm", "tdp": 240, "noise_level": "30dBA", "tier_score": 6},
  {"name": "九州风神 AK620 DIGITAL", "brand": "九州风神", "cooler_type": "双塔", "height": 160, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 280, "noise_level": "30dBA", "tier_score": 8},
  {"name": "九州风神 AK620 DIGITAL WH", "brand": "九州风神", "cooler_type": "双塔", "height": 160, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 280, "noise_level": "30dBA", "tier_score": 8},
  {"name": "九州风神 AK620 DIGITAL PRO", "brand": "九州风神", "cooler_type": "双塔", "height": 162, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 300, "noise_level": "30dBA", "tier_score": 8},
  {"name": "九州风神 阿萨辛4S WH", "brand": "九州风神", "cooler_type": "双塔", "height": 164, "fan_count": 2, "radiator_size": "140mm+120mm", "tdp": 300, "noise_level": "22dBA", "tier_score": 9},
  {"name": "九州风神 玄冰AG620", "brand": "九州风神", "cooler_type": "双塔", "height": 157, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 260, "noise_level": "30dBA", "tier_score": 6},
  {"name": "九州风神 玄冰AG620 ARGB WHITE", "brand": "九州风神", "cooler_type": "双塔", "height": 157, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 260, "noise_level": "30dBA", "tier_score": 6},
  {"name": "九州风神 冰阵LP240", "brand": "九州风神", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 280, "noise_level": "30dBA", "tier_score": 6},
  {"name": "九州风神 冰阵LP360", "brand": "九州风神", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 330, "noise_level": "30dBA", "tier_score": 7},
  {"name": "九州风神 冰堡垒240 WH", "brand": "九州风神", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 300, "noise_level": "30dBA", "tier_score": 7},
  {"name": "九州风神 冰堡垒360 WH", "brand": "九州风神", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 350, "noise_level": "30dBA", "tier_score": 8},
  {"name": "九州风神 冰暴240", "brand": "九州风神", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 310, "noise_level": "30dBA", "tier_score": 7},
  {"name": "九州风神 冰暴360", "brand": "九州风神", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 370, "noise_level": "30dBA", "tier_score": 8},
  {"name": "九州风神 LT520 WH", "brand": "九州风神", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 300, "noise_level": "30dBA", "tier_score": 7},
  {"name": "九州风神 LT720 WH", "brand": "九州风神", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 360, "noise_level": "30dBA", "tier_score": 8},
  {"name": "酷冷至尊 Hyper 212 Halo Black", "brand": "酷冷至尊", "cooler_type": "单塔", "height": 154, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "32dBA", "tier_score": 5},
  {"name": "酷冷至尊 Hyper 212 Halo White", "brand": "酷冷至尊", "cooler_type": "单塔", "height": 154, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "32dBA", "tier_score": 5},
  {"name": "酷冷至尊 Hyper 622 Halo Black", "brand": "酷冷至尊", "cooler_type": "双塔", "height": 160, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 260, "noise_level": "32dBA", "tier_score": 7},
  {"name": "酷冷至尊 MasterAir MA624 Stealth", "brand": "酷冷至尊", "cooler_type": "双塔", "height": 160, "fan_count": 2, "radiator_size": "140mm+120mm", "tdp": 280, "noise_level": "32dBA", "tier_score": 8},
  {"name": "酷冷至尊 冰神G240幻境", "brand": "酷冷至尊", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 280, "noise_level": "32dBA", "tier_score": 6},
  {"name": "酷冷至尊 冰神G360幻境", "brand": "酷冷至尊", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 340, "noise_level": "32dBA", "tier_score": 7},
  {"name": "酷冷至尊 冰神P240", "brand": "酷冷至尊", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 300, "noise_level": "32dBA", "tier_score": 7},
  {"name": "酷冷至尊 冰神P360", "brand": "酷冷至尊", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 360, "noise_level": "32dBA", "tier_score": 8},
  {"name": "追风者 PH-TC12DX", "brand": "追风者", "cooler_type": "单塔", "height": 157, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "32dBA", "tier_score": 5},
  {"name": "追风者 PH-TC14PE", "brand": "追风者", "cooler_type": "双塔", "height": 171, "fan_count": 2, "radiator_size": "140mm×2", "tdp": 250, "noise_level": "32dBA", "tier_score": 7},
  {"name": "追风者 Polar T6-120 BK", "brand": "追风者", "cooler_type": "单塔", "height": 157, "fan_count": 1, "radiator_size": "120mm", "tdp": 200, "noise_level": "32dBA", "tier_score": 5},
  {"name": "追风者 Polar S4", "brand": "追风者", "cooler_type": "单塔", "height": 152, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "32dBA", "tier_score": 4},
  {"name": "追风者 Polar ST4 ARGB", "brand": "追风者", "cooler_type": "单塔", "height": 152, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "32dBA", "tier_score": 5},
  {"name": "追风者 Polar ST5", "brand": "追风者", "cooler_type": "单塔", "height": 160, "fan_count": 1, "radiator_size": "120mm", "tdp": 200, "noise_level": "32dBA", "tier_score": 5},
  {"name": "追风者 冰灵240 M25", "brand": "追风者", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 300, "noise_level": "32dBA", "tier_score": 7},
  {"name": "追风者 冰灵360 M25", "brand": "追风者", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 360, "noise_level": "32dBA", "tier_score": 8},
  {"name": "追风者 冰灵One 240 T30", "brand": "追风者", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 320, "noise_level": "32dBA", "tier_score": 8},
  {"name": "追风者 冰灵One 360 T30", "brand": "追风者", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 380, "noise_level": "32dBA", "tier_score": 9},
  {"name": "猫头鹰 NH-D15S", "brand": "猫头鹰", "cooler_type": "双塔", "height": 160, "fan_count": 1, "radiator_size": "140mm", "tdp": 250, "noise_level": "24dBA", "tier_score": 8},
  {"name": "猫头鹰 NH-U12S chromax.black", "brand": "猫头鹰", "cooler_type": "单塔", "height": 158, "fan_count": 1, "radiator_size": "120mm", "tdp": 200, "noise_level": "22dBA", "tier_score": 7},
  {"name": "猫头鹰 NH-L9a-AM5", "brand": "猫头鹰", "cooler_type": "下压", "height": 37, "fan_count": 1, "radiator_size": "92mm", "tdp": 95, "noise_level": "23dBA", "tier_score": 4},
  {"name": "海盗船 H150i Elite LCD XT", "brand": "海盗船", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 380, "noise_level": "34dBA", "tier_score": 10},
  {"name": "海盗船 H170i Elite LCD XT", "brand": "海盗船", "cooler_type": "420一体水", "height": 0, "fan_count": 3, "radiator_size": 420, "tdp": 400, "noise_level": "34dBA", "tier_score": 10},
  {"name": "NZXT Kraken 240 RGB", "brand": "恩杰", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 300, "noise_level": "33dBA", "tier_score": 7},
  {"name": "NZXT Kraken 360 Elite", "brand": "恩杰", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 380, "noise_level": "33dBA", "tier_score": 9},
  {"name": "NZXT T120 RGB", "brand": "恩杰", "cooler_type": "单塔", "height": 159, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "28dBA", "tier_score": 5},
  {"name": "瓦尔基里 C240 ARGB", "brand": "瓦尔基里", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 280, "noise_level": "32dBA", "tier_score": 6},
  {"name": "瓦尔基里 C360 ARGB", "brand": "瓦尔基里", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 340, "noise_level": "32dBA", "tier_score": 7},
  {"name": "瓦尔基里 V360白", "brand": "瓦尔基里", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 380, "noise_level": "30dBA", "tier_score": 9},
  {"name": "瓦尔基里 GL240 ARGB", "brand": "瓦尔基里", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 300, "noise_level": "32dBA", "tier_score": 7},
  {"name": "瓦尔基里 GL360 ARGB", "brand": "瓦尔基里", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 360, "noise_level": "32dBA", "tier_score": 8},
  {"name": "乔思伯 CR-1400 EVO ARGB", "brand": "乔思伯", "cooler_type": "单塔", "height": 148, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "乔思伯 CR-1000 V2 PRO ARGB", "brand": "乔思伯", "cooler_type": "单塔", "height": 154, "fan_count": 1, "radiator_size": "120mm", "tdp": 190, "noise_level": "30dBA", "tier_score": 5},
  {"name": "乔思伯 HX6240", "brand": "乔思伯", "cooler_type": "单塔", "height": 162, "fan_count": 1, "radiator_size": "120mm", "tdp": 230, "noise_level": "30dBA", "tier_score": 6},
  {"name": "先马 KW360", "brand": "先马", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 350, "noise_level": "30dBA", "tier_score": 8},
  {"name": "爱国者 冰魄 CP360", "brand": "爱国者", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 330, "noise_level": "30dBA", "tier_score": 7},
  {"name": "爱国者 银河 T240", "brand": "爱国者", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 280, "noise_level": "30dBA", "tier_score": 6},
  {"name": "ID-COOLING SE-214-XT ARGB", "brand": "ID-COOLING", "cooler_type": "单塔", "height": 150, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "ID-COOLING SE-226-XT BLACK", "brand": "ID-COOLING", "cooler_type": "单塔", "height": 156, "fan_count": 1, "radiator_size": "120mm", "tdp": 200, "noise_level": "30dBA", "tier_score": 6},
  {"name": "ID-COOLING FROSTFLOW X240", "brand": "ID-COOLING", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 280, "noise_level": "30dBA", "tier_score": 6},
  {"name": "ID-COOLING FROSTFLOW X360", "brand": "ID-COOLING", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 340, "noise_level": "30dBA", "tier_score": 7},
  {"name": "ID-COOLING SL360 SPACE", "brand": "ID-COOLING", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 360, "noise_level": "30dBA", "tier_score": 8},
  {"name": "超频三 东海 K4000", "brand": "超频三", "cooler_type": "单塔", "height": 155, "fan_count": 1, "radiator_size": "120mm", "tdp": 190, "noise_level": "30dBA", "tier_score": 5},
  {"name": "超频三 东海 R4000W ARGB", "brand": "超频三", "cooler_type": "单塔", "height": 155, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "超频三 巨浪240", "brand": "超频三", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 280, "noise_level": "30dBA", "tier_score": 6},
  {"name": "超频三 棱镜360", "brand": "超频三", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 340, "noise_level": "30dBA", "tier_score": 7},
  {"name": "德商德静界 Dark Rock Pro 5", "brand": "德商德静界", "cooler_type": "双塔", "height": 168, "fan_count": 2, "radiator_size": "120mm+135mm", "tdp": 270, "noise_level": "24dBA", "tier_score": 8},
  {"name": "德商德静界 Dark Rock Elite", "brand": "德商德静界", "cooler_type": "双塔", "height": 168, "fan_count": 2, "radiator_size": "135mm×2", "tdp": 280, "noise_level": "25dBA", "tier_score": 9},
  {"name": "德商德静界 Pure Loop 2 FX 360", "brand": "德商德静界", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 360, "noise_level": "33dBA", "tier_score": 8},
  {"name": "雅浚 B3 PRO ARGB", "brand": "雅浚", "cooler_type": "单塔", "height": 153, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "雅浚 G5", "brand": "雅浚", "cooler_type": "单塔", "height": 155, "fan_count": 1, "radiator_size": "120mm", "tdp": 200, "noise_level": "30dBA", "tier_score": 5},
  {"name": "银欣 Hydrogon D120 ARGB", "brand": "银欣", "cooler_type": "双塔", "height": 155, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 250, "noise_level": "30dBA", "tier_score": 6},
  {"name": "银欣 IceMyst 360", "brand": "银欣", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 350, "noise_level": "30dBA", "tier_score": 8},
  {"name": "联力 极圈 II LCD 360", "brand": "联力", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 370, "noise_level": "30dBA", "tier_score": 9},
  {"name": "联力 极圈 II LCD 240", "brand": "联力", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 320, "noise_level": "30dBA", "tier_score": 7},
  {"name": "安钛克 Vortex 360 ARGB", "brand": "安钛克", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 340, "noise_level": "30dBA", "tier_score": 7},
  {"name": "安钛克 Symphony 360 ARGB", "brand": "安钛克", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 360, "noise_level": "30dBA", "tier_score": 8},
  {"name": "采融 A3", "brand": "采融", "cooler_type": "单塔", "height": 153, "fan_count": 1, "radiator_size": "120mm", "tdp": 180, "noise_level": "30dBA", "tier_score": 5},
  {"name": "大镰刀 千石船", "brand": "大镰刀", "cooler_type": "双塔", "height": 160, "fan_count": 2, "radiator_size": "120mm×2", "tdp": 260, "noise_level": "30dBA", "tier_score": 7},
  {"name": "华硕 ROG RYUJIN III 360 ARGB", "brand": "华硕", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 380, "noise_level": "33dBA", "tier_score": 9},
  {"name": "华硕 TUF GAMING LC II 360 ARGB", "brand": "华硕", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 350, "noise_level": "30dBA", "tier_score": 7},
  {"name": "技嘉 AORUS WATERFORCE X II 360", "brand": "技嘉", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 370, "noise_level": "30dBA", "tier_score": 8},
  {"name": "九州风神 冰魔方240 WH", "brand": "九州风神", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 300, "noise_level": "30dBA", "tier_score": 7},
  {"name": "九州风神 玄冰500", "brand": "九州风神", "cooler_type": "单塔", "height": 158, "fan_count": 1, "radiator_size": "120mm", "tdp": 210, "noise_level": "30dBA", "tier_score": 6},
  {"name": "海盗船 iCUE H100i Elite Capellix XT", "brand": "海盗船", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 320, "noise_level": "34dBA", "tier_score": 8},
  {"name": "猫头鹰 NH-D15 G2 LBC", "brand": "猫头鹰", "cooler_type": "双塔", "height": 168, "fan_count": 2, "radiator_size": "140mm×2", "tdp": 300, "noise_level": "24dBA", "tier_score": 9},
  {"name": "利民 TA120 EX BLACK", "brand": "利民", "cooler_type": "单塔", "height": 157, "fan_count": 1, "radiator_size": "120mm", "tdp": 230, "noise_level": "30dBA", "tier_score": 6},
  {"name": "利民 AXP90-X47", "brand": "利民", "cooler_type": "下压", "height": 47, "fan_count": 1, "radiator_size": "92mm", "tdp": 110, "noise_level": "25dBA", "tier_score": 3},
  {"name": "利民 AXP90-X53 FULL", "brand": "利民", "cooler_type": "下压", "height": 53, "fan_count": 1, "radiator_size": "92mm", "tdp": 130, "noise_level": "26dBA", "tier_score": 4},
  {"name": "ID-COOLING IS-55 ARGB", "brand": "ID-COOLING", "cooler_type": "下压", "height": 57, "fan_count": 1, "radiator_size": "120mm(薄)", "tdp": 160, "noise_level": "30dBA", "tier_score": 4},
  {"name": "追风者 PH-TC14PE WHITE", "brand": "追风者", "cooler_type": "双塔", "height": 171, "fan_count": 2, "radiator_size": "140mm×2", "tdp": 250, "noise_level": "30dBA", "tier_score": 7},
  {"name": "NZXT Kraken 360", "brand": "NZXT", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 360, "noise_level": "33dBA", "tier_score": 8},
  {"name": "Arctic Liquid Freezer III 360", "brand": "Arctic", "cooler_type": "360一体水", "height": 0, "fan_count": 3, "radiator_size": 360, "tdp": 370, "noise_level": "23dBA", "tier_score": 8},
  {"name": "Arctic Liquid Freezer III 240", "brand": "Arctic", "cooler_type": "240一体水", "height": 0, "fan_count": 2, "radiator_size": 240, "tdp": 320, "noise_level": "23dBA", "tier_score": 7},
  {"name": "Arctic Freezer 36 ARGB", "brand": "Arctic", "cooler_type": "单塔", "height": 159, "fan_count": 1, "radiator_size": "120mm", "tdp": 200, "noise_level": "30dBA", "tier_score": 6}
];
